version: '3'
services:
  # RED TEAM INFRA
  c2:
    build: c2/.
    hostname: c2.local
    ports:
     - '50050:50050'
    networks:
      dmz:
        ipv4_address: 1.2.3.2
  # BLUE TEAM INFRA
  # edr:
  #   build: edr/.
  #   hostname: edr.local
  #   networks:
  #     dmz:
  #       ipv4_address: 1.2.3.10
  # VULNERABLE MACHINES
  knasty:
    build: knasty/.
    hostname: knasty.local
    ports:
      - '1017:1017'
    networks:
      dmz:
        ipv4_address: 1.2.3.17
  juiceshop:
    image: bkimminich/juice-shop
    hostname: juiceshop.corp
    ports:
      - '3000:3000'
    networks:
      corp:
        ipv4_address: 1.1.1.16
  travesty:
    image: httpd:2.4.49
    hostname: travesty.local
    volumes:
      - ./travesty/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./travesty/index.html:/usr/local/apache2/htdocs/index.html
      - ./travesty/get_time.pl:/usr/local/apache2/cgi-bin/get_time.pl
      - ./travesty/backups.sh:/home/backups.sh
      - ./travesty/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    ports:
      - '80:80'
    networks:
      dmz:
        ipv4_address: 1.2.3.15
      corp:
        ipv4_address: 1.1.1.15
  # webgoat:
  #   image: webgoat/goatandwolf
  #   hostname: webgoat.local
  #   ports:
  #     - '8080:8080'
  #     - '9090:9090'
  # metasploitable:
  #   image: tleemcjr/metasploitable2
  #   hostname: metasploitable.local
  #   ports:
  #     - '80:80'
networks:
  dmz:
    ipam:
      config:
        - subnet: 1.2.3.1/24
  corp:
    internal: true
    ipam:
      config:
        - subnet: 1.1.1.1/24

